export type CTGovStudy = {
  id:                  string;
  nct_id:              string;
  title:               string;
  brief_summary:       string | null;
  conditions:          string[] | null;
  interventions:       string[] | null;
  intervention_types:  string[] | null;
  phase:               string | null;
  status:              string;
  sponsor_name:        string | null;
  sponsor_class:       string | null;
  start_date:          string | null;
  completion_date:     string | null;
  minimum_age:         string | null;
  maximum_age:         string | null;
  sex:                 string | null;
  healthy_volunteers:  boolean | null;
  enrollment_count:    number | null;
  locations:           unknown;
  eligibility_criteria: string | null;
  contact_name:        string | null;
  contact_email:       string | null;
  contact_phone:       string | null;
  ctgov_url:           string;
  biome_category:      string | null;
  has_compensation:    boolean | null;
  last_synced_at:      string;
  created_at:          string;
};
